apiVersion: v1
kind: Secret
metadata:
  name: pos-db-secret
type: Opaque
stringData:
  username: user
  password: password
  database: pointofsale
---
apiVersion: v1
kind: Secret
metadata:
  name: pos-jwt-secret
type: Opaque
stringData:
  jwt-secret: dev-secret-change-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: pos-service-urls
type: Opaque
stringData:
  auth-service-url: http://auth-service:8082
  order-service-url: http://order-service:8083
  promotion-service-url: http://promotion-service:8084
  payment-service-url: http://payment-service:8085
